### ISSUE TITLE
Installer wipes out LVM volumes before reaching partition disks step

### ISSUE THREAD

**Issue by flapjack0811** [steamos-community/stephensons-rocket#42]
Reproduction steps:
1. In a VM, create a LVM volume group consisting of 1 physical volume and at least 1 logical volume.
2. Reboot and start SteamOS installer in Expert mode.
3. Open the shell and run `blkid`. Verify that the LVM volume is shown.
4. Continue with installer until the "Partition disks" step. The suggested partition layout is shown.
5. Select "Undo changes to partitions". Only one primary partition is shown, set to use as LVM physical volume.
6. Open the shell and run `blkid` again. The LVM volume is gone.

partman log: http://pastebin.com/zzfvT2ex
syslog: http://pastebin.com/sFvQ44Cw

The syslog definitely shows existing volumes being removed without user confirmation:
```
Apr 13 14:44:08 partman-lvm:   Logical volume "root" successfully removed
Apr 13 14:44:08 partman-lvm:   0 logical volume(s) in volume group "vg0" now active
Apr 13 14:44:08 partman-lvm:   Volume group "vg0" successfully removed
Apr 13 14:44:08 partman-lvm:   Labels on physical volume "/dev/sda1" successfully wiped
```
Edit: Forgot to mention, using official 1.0 93plus1 release.

**Comment by sharkwouter** [comment]
This issue seems to no longer exist, but there is still an issue with the current version of Stephenson's Rocket concerning LVM. That issue has, however, been fixed in the git repo and will be included in the next version.

More details on the other bug report found here: https://github.com/steamos-community/stephensons-rocket/issues/114
